// FILENAME: lease.go
package gothrottle

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"time"
)

// Lease errors.
var (
	// ErrLeaseLost is returned when renewing or releasing a lease that the
	// store no longer holds, because it expired or was already released.
	ErrLeaseLost = errors.New("lease is no longer held")

	// ErrNilLease is returned when a nil lease is passed to Renew or Release.
	ErrNilLease = errors.New("lease must not be nil")
)

// defaultLeaseTTL is how long a lease survives without renewal. A process that
// dies mid-job has its capacity reclaimed within this window.
const defaultLeaseTTL = 30 * time.Second

// minLeaseTTL keeps a TTL long enough that the renewal interval (TTL/3) stays
// above typical network jitter.
const minLeaseTTL = time.Second

// Lease is a reservation of capacity held by one job. Unlike a shared counter,
// each lease is individually identified, so releasing one cannot disturb
// another, and an expired lease can be reclaimed without guessing how much
// weight it accounted for.
type Lease struct {
	// Token uniquely identifies this reservation. Release and Renew act on the
	// token, so a stale release from a job whose lease already expired cannot
	// decrement a newer job's reservation.
	Token string
	// LimiterID is the limiter the capacity belongs to.
	LimiterID string
	// Weight is the capacity held.
	Weight int
	// TTL is the window each renewal grants. Renew reuses it so extending a
	// lease never silently changes how long a crashed holder would keep the
	// capacity.
	TTL time.Duration
	// ExpiresAt is when the store will reclaim this lease unless it is renewed.
	// It is the store's clock, not the caller's.
	ExpiresAt time.Time
}

// ttlOrDefault returns the lease's renewal window, falling back to the package
// default for a lease built without one.
func (l *Lease) ttlOrDefault() time.Duration {
	if l.TTL > 0 {
		return l.TTL
	}
	return defaultLeaseTTL
}

// LeaseDatastore is a Datastore that tracks individual reservations rather than
// a single shared counter.
//
// A counter cannot express "this job is still running": the only way to keep
// state from leaking after a crash is to expire it, and expiring a counter while
// a job is still running lets another job start over the limit. Per-lease expiry
// with renewal separates "the holder is gone" from "the holder is slow".
//
// A store may implement this alongside Datastore; the limiter uses the lease
// path when available and falls back to Request/RegisterDone otherwise.
type LeaseDatastore interface {
	Datastore

	// Acquire reserves weight for limiterID. When capacity is unavailable it
	// returns a nil lease and, if the wait is bounded (a MinTime window),
	// how long to wait before retrying.
	Acquire(ctx context.Context, limiterID string, weight int, opts Options) (lease *Lease, retryAfter time.Duration, err error)

	// Renew extends a lease's expiry. It returns ErrLeaseLost if the lease has
	// already expired or been released, which means the capacity has been
	// handed to someone else and the caller is now over the limit.
	Renew(ctx context.Context, lease *Lease) error

	// Release returns a lease's capacity. Releasing an unknown or expired lease
	// is not an error: the store has already reclaimed it, and reporting a
	// failure would only invite a retry that cannot help.
	Release(ctx context.Context, lease *Lease) error
}

// leaseTTL returns the effective lease duration for these options.
func (o Options) leaseTTL() time.Duration {
	ttl := o.LeaseTTL
	if ttl <= 0 {
		ttl = defaultLeaseTTL
	}
	if ttl < minLeaseTTL {
		ttl = minLeaseTTL
	}
	return ttl
}

// renewInterval is how often a held lease is renewed. A third of the TTL allows
// two consecutive failures before the lease is lost.
func (o Options) renewInterval() time.Duration {
	interval := o.leaseTTL() / 3
	if interval < 100*time.Millisecond {
		interval = 100 * time.Millisecond
	}
	return interval
}

// newLeaseToken returns an unguessable lease identifier. Tokens are generated by
// the caller so that a lease can be released idempotently: the same token always
// refers to the same reservation, even across a retry.
func newLeaseToken() (string, error) {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("failed to generate lease token: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
